module Pantry.Reports.Help(help) where {

import qualified Data.Text as X;

help :: X.Text;

help = X.unlines . map X.pack $ [
"Usage: pantry command [options] arguments",
"",
"PATTERN CONTROL",
"    -i, --case-insensitive",
"        makes patterns case insensitive",
"    --case-sensitive",
"        makes patterns case sensitive (default)",
"    -v, --invert",
"        invert ordinary matching behavior",
"    --no-invert",
"        do not invert matching behavior (default)",
"    --within",
"        use \"within\" matcher (default)",
"    --posix",
"        use POSIX regular expression matcher",
"    --pcre",
"        use PCRE regular expression matcher",
"    --exact",
"        use \"exact\" matcher",
"",
"FILTERING FOODS FROM VOLATILE",
"    -f tag-name pattern, --find tag-name pattern",
"        Remove all foods without matching tag-name and pattern",
"    --id numbers...",
"        Keep only foods matching ID numbers",
"    --clear",
"        Remove all foods from volatile",
"    --recopy",
"        Replace volatile with foods in database",
"    --head n",
"        Remove all but the first n foods",
"    --tail n",
"        Remove all but the last n foods",
"    --create",
"        Create new blank food in volatile",
"    --move id id [id...]",
"         Rearrange foods with specified IDs into specified sequence",
"    --undo n",
"         Replace volatile with the foods that existed in the database",
"         n changes ago",
"",
"CHANGE TAGS AND PROPERTIES",
"    -c tag-name string, --change-tag tag-name string",
"        Set tag equal to string",
"    --delete-tag tag-name",
"        Delete tag matching tag-name",
"    -u pattern, --change-unit pattern",
"        Change current unit to the one matching pattern",
"    -q number,  --change-quantity number",
"        Change quantity to number, which may be floating point,",
"        a fraction, or a mixed number",
"    --change-percent-refuse number",
"        Change percent refuse to number (between 0 and 100 inclusive)",
"    --change-yield number",
"        Change yield to number, which is a floating-point number",
"    --remove-yield",
"        Let Pantry determine the yield for you",
"",
"    --by-nutrient nut-name qty",
"        set quantity of foods so amount of nut-name = qty",
"    -r, --refuse",
"        reduce quantity of foods by percent refuse",
"",
"CHANGING NUTRIENTS, AVAILABLE UNITS, AND INGREDIENTS",
"    --change-nutrient pattern value",
"        change nutrient value",
"    --rename-nutrient pattern new-name",
"        rename nutrient to new-name",
"    --delete-nutrients pattern",
"        delete nutrients matching pattern",
"",
"    --change-available-unit pattern value",
"        change available unit value",
"    --rename-available-unit pattern new-name",
"        rename available unit matching pattern to new-name",
"    --delete-available-units pattern",
"        delete available units matching regexp",
"",
"INGREDIENTS",
"    --replace-with-ingredients",
"        Replace volatile with the ingredients of the foods",
"        currently in volatile",
"    --remove-ingredients",
"        Remove all ingredients of foods in volatile",
"    --ingredients-to-volatile id [id...]",
"        Add given IDs from the buffer as ingredients",
"        to foods in volatile",
"",
"REPORTING",
"    -p REPORT, --print REPORT",
"        print REPORT, where REPORT is one of:",
"            name - name tag, if food has one",
"            properties - all non-tag properties",
"            units - available units",
"            paste - name, available units, and IDs for cut-and-paste",
"            count-tags - summary of tag information",
"            nutrients - nutrients of each food",
"            total - total nutrients",
"            ingredients - a food's ingredients",
"            tags - the food's tags",
"            blank - a blank line",
"            xml - XML output (maybe for XSLT, or XSL-FO, or . . . )",
"            status - server status",
"            help",
"            version",
"",
"    -g nutrient-name number, --goal nutrient-name number",
"        Show nutrient-name in nutrients and Nutrients reports, with",
"        number used as a goal",
"    --show-all-nutrients",
"        Show all nutrients in nutrients and Nutrients reports,",
"        even if --goal is used",
"    --show-tag tag-name, -t tag-name",
"        Show tag-name in tags and summarize-tags reports",
"    --show-all-tags",
"        Show all tags in tags and summarize-tags reports,",
"        even if --show-tag is used",
"    --one-column",
"        Print values in one column for tags and properties reports",
"",
"SORTING OPTIONS",
"    -k (ascending|descending) tag-name ...",
"        Sort by tag-name in ascending or descending order",
"    -O tag-name value, --key-order tag-name value",
"        Show values for tag-name in a particular order",
"",
"ADDING CHANGED FOODS",
"These commands affect the buffer; they do not affect volatile.",
"    -a, --append",
"        Add volatile to the end of the buffer",
"    --prepend",
"        Add volatile to the beginning of the buffer",
"    --replace",
"        Replace buffer with volatile",
"    --edit",
"        Replace foods in buffer with foods in volatile with same ID",
"    --delete",
"        Delete foods in buffer that have ID of food in volatile",
"    --ingredients-from-volatile id [id...]",
"        Add foods in volatile to foods in buffer with given IDs",
"",
"OPENING AND SAVING FILES",
"    These commands do not affect volatile.",
"    --open filename",
"        Replace database with one from filename",
"    --append-file filename",
"        Add contents of filename to end of the database",
"    --prepend-file filename",
"        Prepend contents of filename to beginning of database",
"    --close",
"        Close currently open database",
"    --save",
"        Save database to its current filename",
"    --save-as filename",
"        Save database to given filename",
"    --quit",
"        Shut down server",
"",
"HELP",
"Each of these has a corresponding --print option.",
"    --help",
"        Show help message",
"    --version",
"        Print version information",
"    --copyright",
"        Print copyright information",
"",
"Pantry home page: http://www.smileystation.com/pantry",
"Report bugs to omari@smileystation.com."
];
}
